# docker-compose.yml
version: '3.8'

services:
  web:
    container_name : server
    build: .
    ports:
      - 5003:5003
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    container_name : database
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: USER_NAME
      POSTGRES_PASSWORD: USER_PASSWORD
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: